### ISSUE TITLE
Remove Comments

### ISSUE THREAD

**Issue by alc5440** [dallen67/Capstone-Group-5.2#1]
I see you copied my code as a basis for building your own (which is fine, it's a good start) but I'd strongly recommend removing all the comments I put in there. I did it to explain what was going on since y'all hadn't coded in python for a while but the sheer volume of comments makes the code hard to read.

**Comment by dallen67** [comment]
Thank you for the feedback. I will be working on cleaning up the code today
so that we can all better read it.

Thanks,
Drew Allen
